FROM ubuntu:16.04
#sudo docker build -t chen116/mibench/network/dijkstra .
# RUN apt-get install all_my_dependencies
RUN apt-get update
RUN apt-get -y install build-essential libnuma-dev
#RUN apt-get -y install sudo
#ADD dijkstra_small /
#ADD input.dat /
#COPY linpack /
COPY heartbeats /heartbeats
ENV  HEARTBEAT_ENABLED_DIR /heartbeats/hbed
RUN cd heartbeats && make clean && make uninstall && make && make install && ld$
COPY stream-vic /stream-vic
RUN cd stream-vic && make

#CMD ["pwd"]
#CMD ["ls"]
#CMD ["./dijkstra_small","input.dat",">","output.txt"]
#CMD ["./dijkstra_small","input.dat"]
#CMD ["touch","hey"]
#CMD ["ls"]
#CMD tail -f /dev/null
#CMD ["./stream-vic/vic && cat ./vic.log"]
#CMD ["cat","./vic.log"]
