FROM debian:stretch
#FROM ubuntu:16.04
RUN apt-get update
RUN apt-get -y install build-essential libnuma-dev
RUN apt-get -y install sudo
RUN apt-get -y install git
RUN apt-get -y install python
RUN git clone git://git.kernel.org/pub/scm/linux/kernel/git/clrkwllms/rt-tests.git
RUN cd rt-tests && make cyclictest
RUN cp ./rt-tests/cyclictest /usr/bin/

# RUN apt-get install all_my_dependencies
#ADD postmark_loop10 /
#ADD con2 /
#CMD ["sudo","./rt-tests/cyclictest", "-p80","-n","-D","3","-h300"]
CMD ["sudo","cyclictest","-l1000","n","-h400"]
#CMD ["./postmark_loop10","con2"]
